(function(){
  const {qs,qsa,esc,fmt,time,badge,icon,toast}=window.GUI;
  const S=()=>window.GStore.get();
  const animal=(s,id)=>s.animals.find(a=>a.id===id)||{};
  const staff=(s,id)=>s.staff.find(a=>a.id===id)||{};
  function go(name,updateHash=true){if(!qs('#'+name))name='dashboard';qsa('.screen').forEach(x=>x.classList.toggle('active',x.id===name));qsa('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));if(updateHash)history.replaceState(null,'','#'+name);scrollTo({top:0,behavior:'smooth'})}
  function statePanel(s){const f=GStore.calculateFacilityState(s);return `<div class="state-card"><div class="state-icon">✓</div><div><p class="eyebrow">Current facility state</p><h2>${esc(f.label)}</h2><p>${esc(f.reason)}</p></div><div class="traffic"><div class="light"><span class="bulb g ${f.state==='green'?'active':''}"></span>GREEN<br>NORMAL</div><div class="light"><span class="bulb a"></span>AMBER<br>CAUTION</div><div class="light"><span class="bulb r ${f.state==='red'?'active':''}"></span>RED<br>EMERGENCY</div></div></div>`}
  function renderDashboard(s){
    qs('#facilityState').innerHTML=statePanel(s);
    const dogs=s.animals.filter(a=>a.species==='Dog'&&a.status!=='Departed').length,cats=s.animals.filter(a=>a.species==='Cat'&&a.status!=='Departed').length;
    const completed=s.rounds.filter(r=>r.status==='Completed').length,openAlerts=s.alerts.filter(a=>a.status==='Open').length,on=s.staff.filter(x=>x.onShift).length;
    qs('#dashboardStats').innerHTML=[['🐕','Dogs in care',dogs,`/${s.facility.capacityDogs} capacity`],['🐈','Cats in care',cats,`/${s.facility.capacityCats} capacity`],['⇩','Check-ins today',s.bookings.filter(b=>b.type==='Drop-off').length,'including scheduled'],['⇧','Check-outs today',s.bookings.filter(b=>b.type==='Pick-up').length,'including scheduled'],['✓','Rounds completed',`${completed}/${s.rounds.length}`,`${Math.round(completed/s.rounds.length*100)}%`],['⚠','Active alerts',openAlerts,openAlerts?'controlled / assigned':'all clear'],['♟','Staff on duty',on,'view roster']].slice(0,6).map(x=>`<div class="stat"><span class="mini-icon">${x[0]}</span><small>${x[1]}</small><b>${x[2]}</b><small>${x[3]}</small></div>`).join('');
    qs('#bookingList').innerHTML=s.bookings.slice().sort((a,b)=>new Date(a.time)-new Date(b.time)).map(b=>{const a=animal(s,b.animalId);return `<div class="row"><div class="species-icon">${icon(a.species)}</div><div class="row-grow"><b>${esc(a.name)} · ${esc(b.type)}</b><small>${esc(a.breed||'')} · ${fmt(b.time)}</small></div>${badge(b.status,b.status==='Completed'?'green':'yellow')}</div>`}).join('');
    qs('#roundList').innerHTML=s.rounds.map(r=>`<div class="row"><div class="species-icon">${r.status==='Completed'?'✓':'◷'}</div><div class="row-grow"><b>${esc(r.zone)}</b><small>${esc(r.species)} · ${esc(staff(s,r.assignedTo).name||'Unassigned')} · due ${time(r.due)}</small><div class="progress"><span style="width:${r.progress||0}%"></span></div></div>${badge(r.status,r.status==='Completed'?'green':r.status==='In progress'?'amber':'outline')}</div>`).join('');
    qs('#alertList').innerHTML=s.alerts.filter(a=>a.status==='Open').map(a=>`<div class="row"><div class="species-icon">${a.severity==='red'?'!':'⚠'}</div><div class="row-grow"><b>${esc(a.title)}</b><small>${esc(a.detail)} · owner: ${esc(a.owner||'unassigned')}</small></div>${badge(a.severity.toUpperCase(),a.severity)}</div>`).join('')||'<div class="alert-box green"><h3>All clear</h3><p>No open alerts.</p></div>';
    qs('#facilitySystems').innerHTML=[['🔒','Gates & doors','All secure','green'],['◉','Cameras','12 online','green'],['🌡','Temperature','22.1°C','green'],['💧','Humidity','51%','green'],['✚','Med fridge','3.2°C','green'],['⚡','Power','Backup ready','green']].map(x=>`<div class="row"><div class="species-icon">${x[0]}</div><div class="row-grow"><b>${x[1]}</b><small>${x[2]}</small></div>${badge('OK',x[3])}</div>`).join('');
  }
  function renderAnimals(s){qs('#animalCards').innerHTML=s.animals.map(a=>`<article class="card watermark"><div class="row"><${a.photo?'img':'div'} ${a.photo?`src="${esc(a.photo)}" alt="${esc(a.name)}" class="avatar"`:`class="species-icon"`}>${a.photo?'':icon(a.species)}</${a.photo?'img':'div'}><div class="row-grow"><h2 style="margin:0">${esc(a.name)}</h2><small>${esc(a.species)} · ${esc(a.breed)} · ${esc(a.sex)} · ${esc(a.age||'')}</small></div>${badge(a.light.toUpperCase(),a.light)}</div><div class="grid two small"><p><b>Status:</b><br>${esc(a.status)} · ${esc(a.room)}</p><p><b>Owner:</b><br>${esc(a.owner)}</p><p><b>Vaccination:</b><br>${esc(a.vaccination||'Not entered')}</p><p><b>Allergies:</b><br>${esc(a.allergies||'None entered')}</p><p><b>Diet:</b><br>${esc(a.diet||'Not entered')}</p><p><b>Medication:</b><br>${esc(a.medication||'None')}</p></div><div class="alert-box ${a.light==='amber'?'':'green'}"><h3>Safe handling and behaviour</h3><p>${esc(a.behaviour||'No special instruction entered')}</p></div><p class="small"><b>Authorised pickup:</b> ${esc(a.pickupAuthorised||'Not entered')}</p></article>`).join('')}
  function renderBookings(s){qs('#bookingTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Animal</th><th>Species</th><th>Movement</th><th>Date/time</th><th>Status</th><th>Owner</th></tr></thead><tbody>${s.bookings.map(b=>{const a=animal(s,b.animalId);return `<tr><td>${esc(a.name)}</td><td>${esc(a.species)}</td><td>${esc(b.type)}</td><td>${fmt(b.time)}</td><td>${badge(b.status,b.status==='Completed'?'green':'yellow')}</td><td>${esc(a.owner||'')}</td></tr>`}).join('')}</tbody></table></div>`}
  function renderCustody(s){const rows=s.audit.filter(a=>/custody|drop-off|pick-up/i.test(a.action+' '+a.detail)).slice(0,20);qs('#custodyLog').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Time</th><th>Employee</th><th>Action</th><th>Record</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${fmt(x.time)}</td><td>${esc(x.actor)}</td><td>${esc(x.action)}</td><td>${esc(x.detail)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="small">Complete a drop-off or pick-up to create the custody record.</p>'}
  function renderRooms(s){qs('#roomCards').innerHTML=s.rooms.map(r=>{const a=animal(s,r.occupiedBy);return `<article class="card"><div class="card-head"><h2>${esc(r.name)}</h2>${badge(r.state.toUpperCase(),r.state)}</div><p class="small">${esc(r.species)} · ${esc(r.type)}</p><div class="grid two small"><p><b>Occupant</b><br>${a.name?`${icon(a.species)} ${esc(a.name)}`:'Available'}</p><p><b>Gate / door</b><br>${esc(r.gate)}</p><p><b>Temperature</b><br>${r.temperature}°C</p><p><b>Humidity</b><br>${r.humidity}%</p></div>${r.state!=='green'?'<div class="alert-box"><h3>Control required</h3><p>Read the room and animal instructions before entry or transfer.</p></div>':''}</article>`}).join('')}
  function assessPlacement(a,r,s){
    const reasons=[],controls=[];let sev='green',label='GREEN — suitable with normal checks';
    if(r.species!=='Both'&&r.species!==a.species){sev='red';label='RED — do not place';reasons.push('Room is assigned to a different species')}
    if(r.occupiedBy&&r.occupiedBy!==a.id){sev='red';label='RED — occupied';reasons.push('Room already has another animal')}
    if(a.species==='Dog'){
      if(/reactive|two-person/i.test(a.behaviour||'')&&!/Quiet|Isolation|Medical/i.test(r.type)){sev=sev==='red'?sev:'amber';label='AMBER — controls or different run required';reasons.push('Behaviour profile needs a lower-traffic placement');controls.push('Use two trained staff for movement')}
      if(/heat|brachy/i.test(a.behaviour||'')&&r.temperature>24){sev='amber';reasons.push('Higher temperature for a heat-risk dog');controls.push('Use climate-controlled room and frequent checks')}
    }else if(a.species==='Cat'){
      if(!/Cat|Isolation|Medical|Quiet|Senior|Escape/i.test(r.name+' '+r.type)){sev=sev==='red'?sev:'amber';label='AMBER — cat-specific controls required';reasons.push('Room does not show cat-specific escape and comfort controls')}
      if(/escape/i.test(a.behaviour||'')&&!/Escape|Isolation/i.test(r.type)){sev=sev==='red'?sev:'amber';reasons.push('Cat profile identifies an escape risk');controls.push('Use airlock/secondary door and carrier transfer')}
      if(/hiding|low handling/i.test(a.behaviour||'')&&!/Quiet|Senior|Medical/i.test(r.type)){sev=sev==='red'?sev:'yellow';label='YELLOW — monitor and add comfort controls';reasons.push('Cat needs low traffic, hiding and gentle handling');controls.push('Provide hiding box and minimise handling')}
    }
    if(a.vaccination&&a.vaccination!=='Current'){sev=sev==='red'?sev:'amber';label='AMBER — admission control required';reasons.push('Vaccination evidence is not confirmed');controls.push('Supervisor verifies evidence before admission')}
    if(a.medicalPriority&&!/Medical|Senior|Quiet|Isolation/i.test(r.type)){sev=sev==='red'?sev:'yellow';reasons.push('Medical-priority animal may need closer access and monitoring');controls.push('Confirm care plan and round frequency')}
    return {sev,label,reasons:reasons.length?reasons:['No incompatible species, occupancy or profile flags identified'],controls:controls.length?controls:['Normal identity, room and welfare checks']}
  }
  function renderMatching(s){
    const room=qs('#matchRoom');if(room){const v=room.value;room.innerHTML=s.rooms.map(r=>`<option value="${r.id}">${esc(r.name)} · ${esc(r.species)} · ${esc(r.type)}</option>`).join('');if(v)room.value=v}
    qs('#matchingTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Animal</th><th>Current placement</th><th>Species-specific observation</th><th>Suggested control</th></tr></thead><tbody>${s.animals.filter(a=>a.status!=='Departed').map(a=>{const r=s.rooms.find(r=>r.name===a.room)||s.rooms.find(r=>r.occupiedBy===a.id);const obs=a.species==='Cat'?'Check escape control, hiding, litter, noise and dog separation':'Check reactivity, gate movement, play style, heat and staffing';const control=(a.light==='amber'||a.light==='yellow')?'Supervisor review before movement':'Continue normal welfare rounds';return `<tr><td>${icon(a.species)} ${esc(a.name)}</td><td>${esc(r?r.name:a.room||'Unassigned')}</td><td>${esc(obs)}</td><td>${badge(control,a.light==='green'?'green':'amber')}</td></tr>`}).join('')}</tbody></table></div>`
  }
  function renderTasks(s){qs('#taskList').innerHTML=s.tasks.map(t=>{const a=animal(s,t.animalId),st=staff(s,t.assignedTo);return `<div class="row"><div class="species-icon">${a.name?icon(a.species):'⌂'}</div><div class="row-grow"><b>${esc(t.type)}${a.name?' — '+esc(a.name):''}</b><small>${esc(t.detail)} · ${fmt(t.due)} · ${esc(st.name||'Unassigned')}</small></div>${badge(t.status,t.status==='Done'?'green':t.severity)}${t.status!=='Done'?`<button class="btn sm secondary" data-complete-task="${t.id}">Complete</button>`:''}</div>`}).join('');qs('#healthTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Animal</th><th>Species</th><th>Medical / medication</th><th>Diet / allergy</th><th>Behaviour / mobility</th></tr></thead><tbody>${s.animals.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.species)}</td><td>${esc(a.medication||'None')}</td><td>${esc(a.diet||'')}<br><small>${esc(a.allergies||'')}</small></td><td>${esc(a.behaviour||'')}</td></tr>`).join('')}</tbody></table></div>`}
  function renderStock(s){if(!qs('#stockTable'))return;qs('#stockTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Category</th><th>Item</th><th>Quantity</th><th>Minimum</th><th>Expiry</th><th>State</th></tr></thead><tbody>${s.stock.map(x=>{const low=Number(x.quantity)<Number(x.minimum),sev=low?'amber':x.state||'green';return `<tr><td>${esc(x.category)}</td><td>${esc(x.item)}</td><td>${esc(x.quantity)} ${esc(x.unit)}</td><td>${esc(x.minimum)}</td><td>${esc(x.expiry||'Not applicable')}</td><td>${badge(low?'LOW STOCK':'CURRENT',sev)}</td></tr>`}).join('')}</tbody></table></div>`}
  function renderRounds(s){qs('#roundTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Zone</th><th>Species</th><th>Employee</th><th>Due</th><th>Progress</th><th>Status</th></tr></thead><tbody>${s.rounds.map(r=>`<tr><td>${esc(r.zone)}</td><td>${esc(r.species)}</td><td>${esc(staff(s,r.assignedTo).name||'Unassigned')}</td><td>${fmt(r.due)}</td><td><div class="progress"><span style="width:${r.progress||0}%"></span></div><small>${r.progress||0}%</small></td><td>${badge(r.status,r.status==='Completed'?'green':r.status==='In progress'?'amber':'outline')}</td></tr>`).join('')}</tbody></table></div>`}
  function renderTransport(s){qs('#transportList').innerHTML=s.transports.map(t=>{const a=animal(s,t.animalId),d=staff(s,t.driverId);return `<div class="row"><div class="species-icon">${icon(a.species)}</div><div class="row-grow"><b>${esc(t.direction)} — ${esc(a.name)}</b><small>${fmt(t.due)} · ${esc(d.name||'Unassigned')} · ${esc(t.vehicle)} · ${esc(t.crate)}</small></div>${badge(t.status,t.status==='Completed'?'green':'yellow')}</div>`}).join('')}
  function renderStaff(s){qs('#staffList').innerHTML=s.staff.map(x=>`<div class="row"><div class="species-icon">♟</div><div class="row-grow"><b>${esc(x.name)}</b><small>${esc(x.role)} · ${x.firstAid?'Human first aid · ':''}${x.animalFirstAid?'Animal first aid':''}</small></div>${badge(x.onShift?'ON SHIFT':'OFF SHIFT',x.onShift?'green':'outline')}</div>`).join('')}
  function renderEmergency(s){if(!qs('#emergencyStatus'))return;const e=s.emergency||{active:false,checks:{}};qs('#emergencyStatus').innerHTML=badge(e.active?'ACTIVE — '+e.type:'READY',e.active?'red':'green');qs('#headcountTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Animal</th><th>Species</th><th>Status</th><th>Room / last location</th><th>Priority information</th></tr></thead><tbody>${s.animals.filter(a=>a.status!=='Departed').map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.species)}</td><td>${esc(a.status)}</td><td>${esc(a.room)}</td><td>${esc([a.medication&&a.medication!=='None'?'Medication':'',a.behaviour||''].filter(Boolean).join(' · '))}</td></tr>`).join('')}</tbody></table></div>`;if(e.active){const counts=`${s.animals.filter(a=>a.species==='Dog'&&a.status!=='Departed').length} dogs · ${s.animals.filter(a=>a.species==='Cat'&&a.status!=='Departed').length} cats`;const steps=['Call 000 or follow official directions where required','Manager takes command and confirms staff roles','Complete register headcount: '+counts,'Separate dogs and cats; prepare leads, carriers, medication and ID','Move highest-risk and medical animals first','Confirm staff and visitor headcount','Record owner/vet/emergency communications','Preserve incident evidence where safe and lawful'];qs('#emergencyPlan').innerHTML=`<div class="alert-box red"><h3>${esc(e.type)} — ACTIVE</h3><p>Owner: ${esc(e.owner||'Manager')} · started ${fmt(e.startedAt)}</p></div><div class="round-checks" style="margin-top:10px">${steps.map((x,i)=>`<label class="round-check"><input type="checkbox" data-emergency-check="${i}" ${e.checks&&e.checks[i]?'checked':''}><span class="grow">${esc(x)}</span></label>`).join('')}</div>`}else qs('#emergencyPlan').innerHTML='<p class="small">No emergency active. Scenario buttons create a demo plan, red alert and audit record.</p>'}
  function renderIncidents(s){qs('#incidentList').innerHTML=s.incidents.map(i=>{const a=animal(s,i.animalId);return `<div class="row"><div class="species-icon">⚠</div><div class="row-grow"><b>${esc(i.type)}${a.name?' — '+esc(a.name):''}</b><small>${esc(i.detail)} · ${fmt(i.createdAt)} · ${esc(i.status)}</small></div>${badge(i.severity.toUpperCase(),i.severity)}</div>`}).join('')||'<p class="small">No incidents recorded.</p>';qs('#auditList').innerHTML=s.audit.slice(0,60).map(a=>`<div class="row"><div class="row-grow"><b>${esc(a.action)}</b><small>${fmt(a.time)} · ${esc(a.actor)}<br>${esc(a.detail)}</small></div></div>`).join('')}
  function populateOptions(s){qsa('[data-animal-options]').forEach(sel=>{const v=sel.value;sel.innerHTML=s.animals.map(a=>`<option value="${a.id}">${esc(a.name)} · ${esc(a.species)}</option>`).join('');if(v)sel.value=v});qsa('[data-staff-options]').forEach(sel=>{const v=sel.value;sel.innerHTML=s.staff.filter(x=>x.onShift).map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.role)}</option>`).join('');if(v)sel.value=v});const incidentAnimal=qs('#incidentForm [name=animalId]');if(incidentAnimal){const v=incidentAnimal.value;incidentAnimal.innerHTML='<option value="">Facility / no animal</option>'+s.animals.map(a=>`<option value="${a.id}">${esc(a.name)} · ${esc(a.species)}</option>`).join('');if(v)incidentAnimal.value=v}}
  function render(){const s=S();populateOptions(s);renderDashboard(s);renderAnimals(s);renderBookings(s);renderCustody(s);renderRooms(s);renderMatching(s);renderTasks(s);renderStock(s);renderRounds(s);renderTransport(s);renderStaff(s);renderEmergency(s);renderIncidents(s)}
  function openModal(id){qs('#'+id)?.classList.add('open')}
  function closeModal(id){qs('#'+id)?.classList.remove('open')}
  document.addEventListener('DOMContentLoaded',()=>{
    render();
    if(location.hash)go(location.hash.slice(1),false);
    qsa('.nav-btn').forEach(b=>b.addEventListener('click',()=>go(b.dataset.screen)));
    qsa('[data-screen-link]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.screenLink)));
    qsa('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open)));
    qsa('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));
    qsa('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
    qs('#intakeForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const id='a_'+Date.now();GStore.update(s=>{s.animals.push({id,name:f.get('name'),species:f.get('species'),breed:f.get('breed'),sex:f.get('sex'),age:f.get('age'),weight:f.get('weight'),status:'Arriving',room:f.get('room'),light:f.get('vaccination')==='Current'?'green':'yellow',owner:f.get('owner'),vaccination:f.get('vaccination'),diet:f.get('diet'),medication:f.get('medication'),allergies:f.get('allergies'),behaviour:f.get('behaviour'),pickupAuthorised:f.get('pickupAuthorised')});s.bookings.push({id:'b_'+Date.now(),animalId:id,type:'Drop-off',time:new Date(Date.now()+86400000).toISOString(),status:'Due'});if(f.get('vaccination')!=='Current')s.alerts.push({id:'al_'+Date.now(),severity:'yellow',title:`${f.get('name')} vaccination evidence`,detail:'Reception must confirm before admission',owner:'Reception',status:'Open',createdAt:new Date().toISOString()})},'Reception','New booking and intake',`${f.get('name')} · ${f.get('species')}`);e.target.reset();closeModal('intakeModal');toast('Booking and intake saved')});
    qs('#dropoffForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),a=GStore.animal(f.get('animalId')),st=GStore.staff(f.get('staffId'));if(f.get('identity').startsWith('No')){toast('Custody not accepted: identity must be confirmed');return}GStore.update(s=>{const x=s.animals.find(x=>x.id===f.get('animalId'));if(x)x.status='In care';s.bookings.filter(b=>b.animalId===f.get('animalId')&&b.type==='Drop-off').forEach(b=>b.status='Completed')},st.name,'Drop-off custody accepted',`${a.name}; medication: ${f.get('medicationCount')||'none recorded'}; belongings: ${f.get('belongings')||'none recorded'}; arrival: ${f.get('condition')}`);e.target.reset();toast('Drop-off accepted and receipt logged')});
    qs('#pickupForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),a=GStore.animal(f.get('animalId')),st=GStore.staff(f.get('staffId'));GStore.update(s=>{const x=s.animals.find(x=>x.id===f.get('animalId'));if(x)x.status='Departed';s.bookings.filter(b=>b.animalId===f.get('animalId')&&b.type==='Pick-up').forEach(b=>b.status='Completed')},st.name,'Pick-up custody released',`${a.name}; collector: ${f.get('collector')}; authority: ${f.get('authority')}; condition: ${f.get('condition')}`);e.target.reset();toast('Pickup handover logged')});
    qs('#careForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),a=GStore.animal(f.get('animalId'));GStore.update(s=>s.tasks.push({id:'t_'+Date.now(),animalId:f.get('animalId'),type:f.get('type'),detail:f.get('detail'),due:new Date(f.get('due')).toISOString(),status:'Open',assignedTo:f.get('assignedTo'),severity:f.get('severity')}),'Manager','Care task created',`${a.name} · ${f.get('type')}`);e.target.reset();toast('Care task created')});
    qs('#matchForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),st=S(),a=animal(st,f.get('animalId')),r=st.rooms.find(x=>x.id===f.get('roomId')),res=assessPlacement(a,r,st);qs('#matchResult').innerHTML=`<div class="alert-box ${res.sev==='red'?'red':res.sev==='green'?'green':''}"><h3>${esc(res.label)}</h3><p><b>Reasons:</b> ${esc(res.reasons.join('; '))}</p><p><b>Controls:</b> ${esc(res.controls.join('; '))}</p></div>`;GStore.update(s=>{},'Manager','Placement assessment run',`${a.name} → ${r.name}: ${res.label}`)});
    qs('#stockForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),qty=Number(f.get('quantity')),min=Number(f.get('minimum'));GStore.update(s=>s.stock.push({id:'st_'+Date.now(),category:f.get('category'),item:f.get('item'),quantity:qty,unit:f.get('unit'),minimum:min,expiry:f.get('expiry'),state:qty<min?'amber':'green'}),'Manager','Stock item saved',f.get('item'));e.target.reset();toast('Stock item saved')});
    qs('#incidentForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),manager=GStore.staff(f.get('managerId')),a=f.get('animalId')?GStore.animal(f.get('animalId')):null;GStore.update(s=>{s.incidents.unshift({id:'i_'+Date.now(),severity:f.get('severity'),type:f.get('type'),animalId:f.get('animalId'),detail:`${f.get('detail')} Controls: ${f.get('controls')}`,createdAt:new Date().toISOString(),status:'Open'});s.alerts.unshift({id:'al_'+Date.now(),severity:f.get('severity'),title:`Incident: ${f.get('type')}`,detail:a?`${a.name} · ${f.get('detail')}`:f.get('detail'),owner:manager.name,status:'Open',createdAt:new Date().toISOString()})},manager.name,'Incident logged',`${f.get('type')} · ${f.get('severity')}`);e.target.reset();closeModal('incidentModal');toast('Incident logged and manager alerted')});
    document.body.addEventListener('click',e=>{const id=e.target.dataset.completeTask;if(id){GStore.update(s=>{const t=s.tasks.find(x=>x.id===id);if(t)t.status='Done'},'Staff','Care task completed',id);toast('Task completed and audited')}const scenario=e.target.dataset.emergency;if(scenario){GStore.update(s=>{s.emergency={active:true,type:scenario,startedAt:new Date().toISOString(),owner:'Tracey K',checks:{}};s.alerts.unshift({id:'al_'+Date.now(),severity:'red',title:'Emergency active: '+scenario,detail:'Open Emergency Command and follow official directions',owner:'Tracey K',status:'Open',createdAt:new Date().toISOString()})},'Tracey K','Emergency activated',scenario);toast('Emergency plan activated')}});
    document.body.addEventListener('change',e=>{if(e.target.dataset.emergencyCheck!==undefined){const k=e.target.dataset.emergencyCheck;GStore.update(s=>{s.emergency.checks[k]=e.target.checked},'Emergency team','Emergency checklist updated',`${k}: ${e.target.checked?'complete':'reopened'}`)}});
    qs('#standDownEmergency').addEventListener('click',()=>{const st=S();if(!st.emergency.active){toast('No active emergency');return}GStore.update(s=>{const name=s.emergency.type;s.emergency={active:false,type:null,startedAt:null,owner:null,checks:{}};s.alerts.filter(a=>a.status==='Open'&&a.title.startsWith('Emergency active:')).forEach(a=>a.status='Closed');s.tasks.unshift({id:'t_'+Date.now(),animalId:null,type:'Emergency recovery',detail:'Full animal welfare check, headcount, site inspection, evidence export and staff debrief',due:new Date(Date.now()+30*60000).toISOString(),status:'Open',assignedTo:'s1',severity:'amber'})},'Tracey K','Emergency stood down','Recovery task created');toast('Stand-down logged and recovery task created')});
    qs('#exportData').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(S(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='genevieve-cats-dogs-demo-data.json';a.click();URL.revokeObjectURL(a.href)});
    qs('#resetDemo').addEventListener('click',()=>{if(confirm('Reset all demo changes?')){GStore.reset();toast('Demo reset')}});
  });
  window.addEventListener('genevieve:state',render);window.addEventListener('hashchange',()=>go(location.hash.slice(1),false));
})();
