(function(){
 const {qs,qsa,esc,time,badge,icon,toast}=GUI;let employeeId=localStorage.getItem('g_employee')||'s3';let currentRoundId=null;
 const common=[['sighted','Animal physically sighted'],['breathing','Breathing and movement observed'],['water','Fresh water checked'],['food','Food / appetite checked'],['cleanliness','Cleanliness, bedding and waste checked'],['behaviour','Behaviour and stress observed'],['temperature','Temperature / ventilation checked'],['security','Gate, latch or suite door checked'],['medication','Medication status checked'],['notes','Notes or authorised photo considered']];
 const dog=[['toileting','Toileting recorded'],['exercise','Exercise / enrichment reviewed'],['dogTransfer','Dog movement and gate crowding risk checked']];
 const cat=[['litter','Litter tray, urine and faeces checked'],['hiding','Hiding, withdrawal and handling tolerance checked'],['catEscape','Carrier, suite door and escape-control checked']];
 function s(){return GStore.get()}function staffName(st,id){return (st.staff.find(x=>x.id===id)||{}).name||'Employee'}
 function assignedRound(st){return st.rounds.find(r=>r.assignedTo===employeeId&&r.status==='In progress')||st.rounds.find(r=>r.assignedTo===employeeId&&r.status!=='Completed')||st.rounds.find(r=>r.status!=='Completed')}
 function render(){const st=s(),f=GStore.calculateFacilityState(st),emp=st.staff.find(x=>x.id===employeeId)||st.staff[0];employeeId=emp.id;localStorage.setItem('g_employee',employeeId);qs('#employeeSelect').innerHTML=st.staff.filter(x=>x.onShift).map(x=>`<option value="${x.id}" ${x.id===employeeId?'selected':''}>${esc(x.name)} · ${esc(x.role)}</option>`).join('');qs('#employeeState').innerHTML=`<div class="mobile-state"><div class="state-icon">✓</div><div><p class="eyebrow">Current state</p><h2>${esc(f.label)}</h2><p class="small">${esc(f.reason)}</p></div></div>`;
  const r=assignedRound(st);if(!r){qs('#roundTitle').textContent='No round assigned';qs('#roundChecks').innerHTML='';return}currentRoundId=r.id;qs('#roundTitle').textContent=r.zone;qs('#roundStatus').innerHTML=badge(r.status,r.status==='In progress'?'amber':r.status==='Completed'?'green':'outline');qs('#roundMeta').textContent=`${r.species} round · due ${time(r.due)} · ${emp.name}`;qs('#roundProgress').style.width=`${r.progress||0}%`;
  const animals=st.animals.filter(a=>{if(r.species==='Dog')return a.species==='Dog'&&a.status==='In care';if(r.species==='Cat')return a.species==='Cat'&&a.status==='In care';if(r.species==='Both')return a.status==='In care';return false}).slice(0,4);qs('#roundAnimals').innerHTML=animals.map(a=>`<div class="row"><${a.photo?'img':'div'} ${a.photo?`src="${a.photo}" class="avatar" alt="${esc(a.name)}"`:'class="species-icon"'}>${a.photo?'':icon(a.species)}</${a.photo?'img':'div'}><div class="row-grow"><b>${esc(a.name)}</b><small>${esc(a.room)} · ${esc(a.behaviour||'')}</small></div>${badge(a.light.toUpperCase(),a.light)}</div>`).join('')||'<p class="small">This is a facility round.</p>';
  let checks=[...common];if(r.species==='Dog')checks=checks.concat(dog);if(r.species==='Cat')checks=checks.concat(cat);if(r.species==='Both')checks=checks.concat(dog,cat);qs('#roundChecks').innerHTML=checks.map(([k,label])=>`<label class="round-check"><input type="checkbox" data-check="${k}" ${r.checks&&r.checks[k]?'checked':''}><span class="grow">${esc(label)}</span></label>`).join('');
  const tasks=st.tasks.filter(t=>t.assignedTo===employeeId&&t.status!=='Done');qs('#taskCount').textContent=tasks.length;qs('#employeeTasks').innerHTML=tasks.map(t=>{const a=st.animals.find(x=>x.id===t.animalId)||{};return `<div class="row"><div class="species-icon">${a.name?icon(a.species):'⌂'}</div><div class="row-grow"><b>${esc(t.type)}${a.name?' — '+esc(a.name):''}</b><small>${esc(t.detail)} · ${time(t.due)}</small></div>${badge(t.severity.toUpperCase(),t.severity)}<button class="btn sm secondary" data-task="${t.id}">Done</button></div>`}).join('')||'<p class="small">No open tasks assigned.</p>';
  const ai=qs('#employeeIncidentForm [name=animalId]');ai.innerHTML='<option value="">Facility / no animal</option>'+st.animals.map(a=>`<option value="${a.id}">${esc(a.name)} · ${esc(a.species)}</option>`).join('')}
 function collectChecks(){const out={};qsa('[data-check]').forEach(x=>out[x.dataset.check]=x.checked);return out}
 function saveRound(complete){const sev=qs('input[name=roundSeverity]:checked').value,note=qs('#roundNote').value.trim(),checks=collectChecks(),total=Object.keys(checks).length,done=Object.values(checks).filter(Boolean).length,progress=Math.round(done/total*100);if((sev==='amber'||sev==='red')&&!note){toast('Add an observation note for amber or red');return}if(complete&&done<total){toast('Complete every required check before closing the round');return}const emp=GStore.staff(employeeId);GStore.update(st=>{const r=st.rounds.find(x=>x.id===currentRoundId);r.checks=checks;r.progress=complete?100:progress;r.status=complete?'Completed':'In progress';if(complete)r.completedAt=new Date().toISOString();if(sev!=='green'){st.alerts.unshift({id:'al_'+Date.now(),severity:sev,title:`${r.zone} round — ${sev.toUpperCase()}`,detail:note,owner:'Manager review',status:'Open',createdAt:new Date().toISOString()})}},emp.name,complete?'Round completed':'Round progress saved',`${currentRoundId}; ${sev}; ${note||'no exception'}`);qs('#roundNote').value='';toast(complete?'Round completed and manager updated':'Progress saved and synced')}
 document.addEventListener('DOMContentLoaded',()=>{render();qs('#employeeSelect').addEventListener('change',e=>{employeeId=e.target.value;render()});qsa('[data-jump]').forEach(x=>x.addEventListener('click',()=>qs('#'+x.dataset.jump).scrollIntoView({behavior:'smooth'})));qs('#saveRound').addEventListener('click',()=>saveRound(false));qs('#completeRound').addEventListener('click',()=>saveRound(true));document.body.addEventListener('click',e=>{if(e.target.dataset.task){const emp=GStore.staff(employeeId);GStore.update(st=>{const t=st.tasks.find(x=>x.id===e.target.dataset.task);if(t)t.status='Done'},emp.name,'Employee completed task',e.target.dataset.task);toast('Task completed')}if(e.target.matches('[data-open-incident]'))qs('#employeeIncident').classList.add('open');if(e.target.matches('[data-close-employee-incident]'))qs('#employeeIncident').classList.remove('open')});qs('#sosBtn').addEventListener('click',()=>{if(confirm('Raise an urgent internal SOS alert? Call 000 separately for a life-threatening emergency.')){const emp=GStore.staff(employeeId);GStore.update(st=>{st.alerts.unshift({id:'al_'+Date.now(),severity:'red',title:'EMPLOYEE SOS',detail:`Urgent assistance requested by ${emp.name}`,owner:'Manager',status:'Open',createdAt:new Date().toISOString()});st.incidents.unshift({id:'i_'+Date.now(),severity:'red',type:'Employee SOS',animalId:'',detail:'Immediate assistance requested. Manager to establish facts and external response needs.',createdAt:new Date().toISOString(),status:'Open'})},emp.name,'SOS raised','Urgent employee assistance alert');toast('SOS sent to management dashboard')}});qs('#employeeIncidentForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),emp=GStore.staff(employeeId),a=f.get('animalId')?GStore.animal(f.get('animalId')):null;GStore.update(st=>{st.incidents.unshift({id:'i_'+Date.now(),severity:f.get('severity'),type:f.get('type'),animalId:f.get('animalId'),detail:f.get('detail'),createdAt:new Date().toISOString(),status:'Open'});st.alerts.unshift({id:'al_'+Date.now(),severity:f.get('severity'),title:f.get('type'),detail:(a?a.name+' · ':'')+f.get('detail'),owner:'Manager',status:'Open',createdAt:new Date().toISOString()})},emp.name,'Employee incident logged',f.get('type'));e.target.reset();qs('#employeeIncident').classList.remove('open');toast('Incident logged and escalated')})});window.addEventListener('genevieve:state',render)
})();
